modal-windows
p3rfec77/JS-practice-course-module-1 pull request #2
Opened 2023-04-05 16:20 UTC by p3rfec77

вижу что есть какие-то изменения в yarn.lock, видимо я намудрил с npm не поняв сразу, что yarn это менеджер пакетов и npm мне уже не нужен

2023-04-05 16:29 UTC, andrey-kudinov requested changes
Хорошая работа 👍
Есть несколько моментов, которые можно улучшить
Посмотри пж в комментариях

2023-04-05 16:29 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +        const trigger = document.querySelectorAll(triggerSelector);
Хочу обратить твоё внимание на нейминг
В твоём случае здесь массив элементов, поэтому trigger**s**

2023-04-05 16:29 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +        trigger.forEach(item => {
Здесь так же хотел бы обратить внимание на нейминг
Старайся пж придерживаться более говорящего неймига
Тогда код будет более читабельный
На сложный проектах это играет большую роль
```
triggers.forEach(trigger => ...
cards.forEach(card => ...
books.forEach(book => ...
```

2023-04-05 16:29 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +                document.body.style.overflow = "";
```
modal.style.display = 'none';
document.body.style.overflow = '';
```
Эти две строчки повторяются несколько раз, вынеси пж их в отдельную функцию `closeModal` и переиспользуй её
Это будет соответствовать принципу [DRY](https://ru.wikipedia.org/wiki/Don’t_repeat_yourself)
Так же добавь пж закрытие модального окна по клавише `escape`

2023-04-05 16:29 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +    function showModalByTime(selector, time) {
Давай попробуем в этом проекте писать исключительно **стрелочные функции**
Во-первых, практика рефакторинга (довольно простого)
Во-вторых, на мой взгляд, это позволит лучше читать код, так как он будет последовательный
Всегда понятно что за функция будет вызвана, так как она до этого объявлена
Так же на мой взгляд это современнее

2023-04-06 09:45 UTC, andrey-kudinov commented on package-lock.json
этот файл удали пж из пр

2023-04-06 09:46 UTC, andrey-kudinov commented on src/js/modules/modals.js
> +export default modals;
оставляй пж в конце файла пустую строчку

2023-04-06 09:53 UTC, p3rfec77 commented on src/js/modules/modals.js
> +export default modals;
хорошо

2023-04-06 10:08 UTC, merged